# Generated by Django 3.1.1 on 2020-09-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clippingsParser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clip',
            old_name='location',
            new_name='book_location',
        ),
    ]
