# Generated by Django 3.1.1 on 2020-09-08 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clippingsParser', '0002_auto_20200908_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='read_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 21, 11, 12, 444847, tzinfo=utc), verbose_name='book read date'),
        ),
    ]
