# Generated by Django 3.1.1 on 2020-09-09 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clippingsParser', '0003_auto_20200908_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='read_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='book read date'),
        ),
    ]
