# Generated by Django 3.1.1 on 2020-09-25 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clippingsParser', '0004_auto_20200909_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='clippingsParser.library'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clippings', to='clippingsParser.book'),
        ),
    ]
