# Generated by Django 3.1.1 on 2020-11-05 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clippingsParser', '0005_auto_20200925_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='date_read',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
